version: '3'
services:
  api:
    build: .
    command: pytest -v
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'

  db:
    image: postgres:15.1-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'data_test'
      PGUSER: 'postgres'
    expose:
      - '5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 5
  cache:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    depends_on:
      - db
