version: '3'
services:
  homework-1-postgres:
    image: postgres:15.1-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'data'
    ports:
      - '5432:5432'