version: '3'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '8000:8000'

  db:
    image: postgres:15.1-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'data'
    expose:
      - '5432'
  cache:
      image: redis/redis-stack:latest
      ports:
        - '6379:6379'
      depends_on:
        - db
  celery:
      # image: python:3.10-slim
      build: .
      volumes:
      - .:/restaurant_api
      environment:
        TZ: "Europe/Moscow"
        # CELERY_BROKER_URL: "amqp://admin:admin@rabbit"
      command: celery -A app.tasks.tasks worker -B --loglevel=DEBUG
      depends_on:
      - rabbit
  rabbit:
        image: rabbitmq
        # volumes:
        # - .:/celery_tasks
        ports:
        - "5672:5672"
        environment:
          TZ: Europe/Moscow
