version: '3'
services:
  api:
    build: .
    command: pytest -v
    depends_on:
      - db
      - cache
    ports:
      - '8000:8000'

  db:
    image: postgres:15.1-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'data_test'
    expose:
      - '5432'
  cache:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
    depends_on:
      - db
