version: '3'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '8000:8000'

  db:
    image: postgres:15.1-alpine
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'data'
    expose:
      - '5432'
